### ISSUE TITLE
Select a license for the code since it's publicly visible.

### ISSUE THREAD

**Issue by bmd** [jeffiuliano/RiseMap#2]
http://choosealicense.com/

**Comment by jeffiuliano** [comment]
I'd assume we go with an MIT licence, but I'm not 100% sure how to incorporate the fact that some of the code we are using was pulled from elsewhere (see the licence.txt file, which came with the original map code)

**Comment by jeffiuliano** [comment]
I've updated the license.txt specifying and MIT license for our code and keeping the original license for the map that I started with.

**Comment by bmd** [comment]
Yeah - I think that's a good compromise. If it ever becomes an issue, we can revisit in the future.
